function report_lmm21_supplement(results, L, featureAudit)
%REPORT_LMM21_SUPPLEMENT  The supplementary tables the manuscript needs.
%
%   REPORT_LMM21_SUPPLEMENT(RESULTS, L, FEATUREAUDIT) writes the two tables
%   that REPORT_LMM21 does not, plus the intervals of every specification:
%
%     lmm21_sensitivity_table.tex      q of all seven clusters under all specs
%     lmm21_audit_table.tex            one row per participant per cluster
%     lmm21_feature_intervals_all.csv  the 21 intervals under every spec
%
%   The sensitivity table exists because one specification changes the
%   conclusion. Under a by-participant random slope for pressure the primary
%   null does not hold, and a supplement that does not show that is not an
%   honest supplement. The table is therefore the whole grid, not a selection.
%
%   The intervals CSV exists because the standardised bound quoted in the
%   Results comes from the zfeature specification, and RUN_LMM21 writes only
%   the primary specification's intervals to disk. Without this file the
%   number in the manuscript cannot be traced to a file.
%
%   Call it straight after REPORT_LMM21, with the same arguments.
%
%   See also REPORT_LMM21, FIT_LMM21_MODELS, RUN_LMM21.
%
%   Part of the KneeExo-EEG analysis code.

if nargin < 3
    featureAudit = table();
end

outDir = L.files.outDir;
fSens  = fullfile(outDir, 'lmm21_sensitivity_table.tex');
fAudit = fullfile(outDir, 'lmm21_audit_table.tex');
fAllCI = fullfile(outDir, 'lmm21_feature_intervals_all.csv');

labels = containers.Map(L.clusters(:, 1), L.clusters(:, 3));
codes  = containers.Map(L.clusters(:, 1), L.clusters(:, 2));

% =========================================================================
%  Every specification's intervals, so the standardised bound is traceable
% =========================================================================
if isfield(results, 'featureAll') && ~isempty(results.featureAll)
    writetable(results.featureAll, fAllCI);
    fprintf('Wrote %s\n', fAllCI);
end

% =========================================================================
%  The sensitivity table: clusters down, specifications across
% =========================================================================
grid = [results.cluster; results.sensitivity];
specKeys = arrayfun(@(s) string(s.key), L.specs);

% Keep only specifications actually present, in the order LMM21_CONFIG
% declares them, so the primary is the first column.
present = false(size(specKeys));
for s = 1:numel(specKeys)
    present(s) = any(grid.Spec == specKeys(s));
end
specKeys = specKeys(present);

clusterKeys = string(L.clusters(:, 1));

lines = {};
lines{end+1} = '% The sensitivity grid. Generated by report_lmm21_supplement.m.';
lines{end+1} = '\begin{table}[htbp]';
lines{end+1} = '\centering';
lines{end+1} = '\small';
tail = '';
if any(specKeys == "nocov")
    tail = [' The no-covariate column rests on more trials than the others ' ...
        'because it does not require the effort index.'];
end

% Clusters are abbreviated here. Seven full names beside seven columns of
% numbers does not fit the text block, and the abbreviations are the ones
% LMM21_CONFIG already carries, so the legend writes itself.
legend = cell(1, size(L.clusters, 1));
for c = 1:size(L.clusters, 1)
    legend{c} = sprintf('%s, %s', L.clusters{c, 2}, L.clusters{c, 3});
end
tail = [tail ' Clusters: ' strjoin(legend, '; ') '.'];
lines{end+1} = sprintf(['\\caption{\\textbf{Sensitivity of the cluster test to ' ...
    'the specification.} Each column is a complete re-run of all %d cluster ' ...
    'tests with one element of the model changed, corrected within that column ' ...
    'across the %d clusters. Entries are $q$ values; bold marks $q < %.2f$. ' ...
    '%s%s}'], numel(clusterKeys), numel(clusterKeys), L.stats.fdrQ, ...
    spec_legend(L, specKeys), tail);
lines{end+1} = '\label{tab:lmm21sens}';
lines{end+1} = sprintf('\\begin{tabular}{l%s}', repmat('r', 1, numel(specKeys)));
lines{end+1} = '\toprule';

head = cell(1, numel(specKeys));
for s = 1:numel(specKeys)
    head{s} = spec_head(specKeys(s));
end
lines{end+1} = sprintf('Cluster & %s \\\\', strjoin(head, ' & '));
lines{end+1} = '\midrule';

nOfSpec = nan(numel(clusterKeys), numel(specKeys));
for c = 1:numel(clusterKeys)
    cells = cell(1, numel(specKeys));
    for s = 1:numel(specKeys)
        row = grid(grid.Cluster == clusterKeys(c) & grid.Spec == specKeys(s), :);
        if isempty(row) || ~row.Converged(1)
            cells{s} = '--';
            continue
        end
        nOfSpec(c, s) = row.N(1);
        cells{s} = q_string(row.q(1));
        if row.q(1) < L.stats.fdrQ
            cells{s} = sprintf('\\textbf{%s}', cells{s});
        end
    end
    lines{end+1} = sprintf('%s & %s \\\\', ...
        codes(char(clusterKeys(c))), strjoin(cells, ' & ')); %#ok<AGROW>
end

lines{end+1} = '\midrule';
medCells = cell(1, numel(specKeys));
for s = 1:numel(specKeys)
    v = nOfSpec(:, s);
    v = v(isfinite(v));
    if isempty(v)
        medCells{s} = '--';
    else
        medCells{s} = sprintf('%d', round(median(v)));
    end
end
lines{end+1} = sprintf('median $n$ & %s \\\\', strjoin(medCells, ' & '));
lines{end+1} = '\bottomrule';
lines{end+1} = '\end{tabular}';
lines{end+1} = '\end{table}';

write_lines(fSens, lines);
fprintf('Wrote %s\n', fSens);

% =========================================================================
%  The audit table
% =========================================================================
if isempty(featureAudit)
    return
end

lines = {};
lines{end+1} = '% The feature build audit. Generated by report_lmm21_supplement.m.';
lines{end+1} = '\begin{table}[htbp]';
lines{end+1} = '\centering';
lines{end+1} = '\small';
lines{end+1} = ['\caption{\textbf{Construction of the trial-level cortical ' ...
    'features.} One row per participant per cluster. \emph{Cycles} is the ' ...
    'number of movement cycles in that component''s single-trial ' ...
    'time-frequency file; \emph{paired} is how many were matched to a ' ...
    'surviving experiment epoch; \emph{flagged} is how many of those were ' ...
    'rejected by the same trial quality control used for the published ' ...
    'ERSPs; \emph{trials} is the number of trials the surviving cycles were ' ...
    'averaged into.}'];
lines{end+1} = '\label{tab:lmm21audit}';
lines{end+1} = '\begin{tabular}{lrrrrr}';
lines{end+1} = '\toprule';
lines{end+1} = 'Participant & IC & Cycles & Paired & Flagged & Trials \\';
lines{end+1} = '\midrule';

firstBlock = true;
for c = 1:numel(clusterKeys)
    rows = featureAudit(string(featureAudit.Cluster) == clusterKeys(c), :);
    if isempty(rows)
        continue
    end
    rows = sortrows(rows, 'SubjectID');
    if ~firstBlock
        lines{end+1} = '\addlinespace'; %#ok<AGROW>
    end
    firstBlock = false;
    lines{end+1} = sprintf('\\multicolumn{6}{l}{\\textit{%s}} \\\\', ...
        labels(char(clusterKeys(c)))); %#ok<AGROW>
    for r = 1:height(rows)
        lines{end+1} = sprintf('%d & %d & %d & %d & %d & %d \\\\', ...
            rows.SubjectID(r), rows.IC(r), rows.nEpochsFile(r), ...
            rows.nPaired(r), rows.nFlaggedQC(r), rows.nTrials(r)); %#ok<AGROW>
    end
end

lines{end+1} = '\bottomrule';
lines{end+1} = '\end{tabular}';
lines{end+1} = '\end{table}';

write_lines(fAudit, lines);
fprintf('Wrote %s\n', fAudit);

% =========================================================================
%  The accounting sentences the supplementary note quotes
% =========================================================================
inFile  = sum(featureAudit.nEpochsFile);
paired  = sum(featureAudit.nPaired);
flagged = sum(featureAudit.nFlaggedQC);
used    = sum(featureAudit.nUsed);
trials  = sum(featureAudit.nTrials);

fprintf('\n---- Supplementary Note 4, the numbers ----\n');
fprintf('  cycles in the time-frequency files  %d\n', inFile);
fprintf('  matched to an experiment epoch      %d (all but %d)\n', ...
    paired, inFile - paired);
fprintf('  rejected by trial QC                %d (%.1f%%)\n', ...
    flagged, 100 * flagged / max(1, paired));
fprintf('  surviving cycles                    %d\n', used);
fprintf('  trials                              %d\n', trials);
fprintf('  surviving cycles per trial, mean    %.1f\n', used / max(1, trials));
fprintf('  worst pairing residual              %.1f ms\n', ...
    max(featureAudit.maxResidualMs));
fprintf('\n');

end


% ----------------------------------------------------------------------------
function s = q_string(q)
%Q_STRING  A q value that survives \textbf, so no inline maths.

if q < 1e-3
    s = '\textless 0.001';
else
    s = sprintf('%.3f', q);
end

end


% ----------------------------------------------------------------------------
function s = spec_head(key)
%SPEC_HEAD  The column heading for one specification.

switch char(key)
    case 'primary',     s = 'primary';
    case 'zfeature',    s = 'z-scored';
    case 'categorical', s = 'categorical';
    case 'notrial',     s = 'no trial';
    case 'rawcov',      s = 'raw cov.';
    case 'nocov',       s = 'no cov.';
    case 'randslope',   s = 'rand.\ slope';
    otherwise,          s = strrep(char(key), '_', ' ');
end

end


% ----------------------------------------------------------------------------
function s = spec_legend(L, specKeys)
%SPEC_LEGEND  The caption sentence that says what each column changed.
%
%  Deliberately not taken from L.specs(i).note. Those notes are written for
%  the person reading the code; a caption is written for the reader of the
%  paper, and the two should not be forced to be the same sentence. An
%  unrecognised key falls back to its note so that a new specification still
%  appears in the caption rather than silently going unexplained.

parts = cell(1, numel(specKeys));
for i = 1:numel(specKeys)
    switch char(specKeys(i))
        case 'primary'
            t = 'the reported model';
        case 'zfeature'
            t = ['feature in within-participant standard deviations rather ' ...
                'than dB'];
        case 'categorical'
            t = ['pressure with two degrees of freedom rather than as an ' ...
                'equal-step ordinal variable'];
        case 'notrial'
            t = 'trial number removed';
        case 'rawcov'
            t = ['effort and tracking error entered raw rather than split ' ...
                'into within- and between-participant components'];
        case 'nocov'
            t = 'effort and tracking error removed entirely';
        case 'randslope'
            t = ['a by-participant random slope for pressure added to the ' ...
                'random intercept'];
        otherwise
            idx = find(arrayfun(@(x) strcmp(x.key, char(specKeys(i))), ...
                L.specs), 1);
            t = L.specs(idx).note;
    end
    parts{i} = sprintf('\\emph{%s}, %s.', spec_head(specKeys(i)), t);
end
s = strjoin(parts, ' ');

end


% ----------------------------------------------------------------------------
function write_lines(fname, lines)

fid = fopen(fname, 'w');
if fid > 0
    fprintf(fid, '%s\n', strjoin(lines, newline));
    fclose(fid);
end

end