function texFile = report_lmm21_supplement(results, cfg)
%REPORT_LMM21_SUPPLEMENT  Supplementary table and the sentences to paste.
%
%  texFile = REPORT_LMM21_SUPPLEMENT(results, cfg) writes the 21 coefficient
%  supplementary table as LaTeX, grouped by cluster, and prints the two
%  manuscript sentences with the placeholders filled from the fit.
%
%  The placeholders this fills are the ones currently sitting in the results
%  paragraph as \ph{value} and \ph{$\approx 0.06$}, and the exclusion bound in
%  the Discussion. All three come from the same run, so they cannot drift
%  apart the way hand copied numbers do.
%
%  Rounding is done once, here, and the same rounded values go into both the
%  table and the sentences.
%
%  See also RUN_LMM_21FEATURES.

if nargin < 2 || isempty(cfg)
    cfg = results.cfg;
end

P = results.primary;
S = results.summary;

% Order the rows by cluster and band rather than by p, because a
% supplementary table sorted by significance invites reading it as a ranking.
order = featureOrder(cfg);
[~, ia] = ismember(order, cellstr(P.Feature));
ia = ia(ia > 0);
P = P(ia, :);

lookup = featureLookup(cfg);

lines = {};
lines{end+1} = '% Supplementary table: trial level cortical band power and perceived difficulty';
lines{end+1} = '% Generated by report_lmm21_supplement.m, do not edit by hand.';
lines{end+1} = '\begin{table}[htbp]';
lines{end+1} = '\centering';
lines{end+1} = sprintf(['\\caption{Fixed effect of each cortical feature on perceived ' ...
    'difficulty, over and above pressure, tracking error and neuromuscular ' ...
    'effort. Coefficients are rating points per within participant standard ' ...
    'deviation of the feature. $q$ values are Benjamini and Hochberg corrected ' ...
    'across the %d features.}'], height(P));
lines{end+1} = '\label{tab:lmm21}';
lines{end+1} = '\begin{tabular}{llrrrrrr}';
lines{end+1} = '\toprule';
lines{end+1} = 'Cluster & Band & $n$ & $\beta$ & SE & 95\% CI & $p$ & $q$ \\';
lines{end+1} = '\midrule';

lastCluster = '';
for i = 1:height(P)
    key = char(P.Feature(i));
    meta = lookup(key);

    if ~strcmp(meta.cluster, lastCluster)
        if ~isempty(lastCluster)
            lines{end+1} = '\addlinespace'; %#ok<AGROW>
        end
        clusterCell = meta.cluster;
        lastCluster = meta.cluster;
    else
        clusterCell = '';
    end

    if P.Converged(i)
        lines{end+1} = sprintf('%s & %s & %d & $%+.3f$ & %.3f & $[%+.3f, %+.3f]$ & %.3f & %.3f \\\\', ...
            clusterCell, meta.band, P.N(i), P.Estimate(i), P.SE(i), ...
            P.Lower(i), P.Upper(i), P.pValue(i), P.q(i)); %#ok<AGROW>
    else
        lines{end+1} = sprintf('%s & %s & \\multicolumn{6}{c}{model did not fit} \\\\', ...
            clusterCell, meta.band); %#ok<AGROW>
    end
end

lines{end+1} = '\bottomrule';
lines{end+1} = '\end{tabular}';
lines{end+1} = '\end{table}';

tex = strjoin(lines, newline);

texFile = '';
if ~isempty(cfg.paths.out)
    if exist(cfg.paths.out, 'dir') ~= 7
        mkdir(cfg.paths.out);
    end
    texFile = fullfile(cfg.paths.out, cfg.out.supplementTex);
    fid = fopen(texFile, 'w');
    fprintf(fid, '%s\n', tex);
    fclose(fid);
    fprintf('[report_lmm21_supplement] Wrote %s\n', texFile);
end

% -------------------------------------------------------------------------
% The sentences
% -------------------------------------------------------------------------
fprintf('\n---- Results paragraph, placeholders filled ----\n\n');
fprintf(['No cortical feature predicted perceived difficulty beyond these ' ...
    'variables: every coefficient was indistinguishable from zero after ' ...
    'correction (all $q \\geq %.2f$; uncorrected $p \\geq %.2f$).\n'], ...
    S.minQ, S.minP);

fprintf('\n---- Discussion bound ----\n\n');
fprintf(['The widest 95%% interval across the %d features reaches %.2f rating ' ...
    'points per within participant standard deviation, against a demand ' ...
    'effect of 5.20 rating points.\n'], S.nConverged, S.maxAbsCI);

fprintf('\n---- Methods, the two facts that need stating ----\n\n');
fprintf(['  Feature composition: %d clusters by %d bands = %d features.\n'], ...
    numel(cfg.clusters), numel(cfg.bands), numel(cfg.clusters) * numel(cfg.bands));
fprintf('  Clusters: %s\n', strjoin({cfg.clusters.label}, '; '));
fprintf('  Bands: ');
for b = 1:numel(cfg.bands)
    fprintf('%s %g to %g Hz', cfg.bands(b).label, cfg.bands(b).edges(1), ...
        cfg.bands(b).edges(2));
    if b < numel(cfg.bands), fprintf(', '); end
end
fprintf('\n');
if isfield(S, 'randSlopeConverged')
    fprintf(['  Random slope models: %d of %d converged, which is why the ' ...
        'primary model uses a by participant random intercept.\n'], ...
        S.randSlopeConverged, S.randSlopeTotal);
end
fprintf('\n');

end

% =========================================================================
function order = featureOrder(cfg)
order = {};
for c = 1:numel(cfg.clusters)
    for b = 1:numel(cfg.bands)
        order{end+1} = sprintf('%s_%s', cfg.clusters(c).abbr, cfg.bands(b).name); %#ok<AGROW>
    end
end
end

% -------------------------------------------------------------------------
function m = featureLookup(cfg)
m = containers.Map('KeyType', 'char', 'ValueType', 'any');
for c = 1:numel(cfg.clusters)
    for b = 1:numel(cfg.bands)
        key = sprintf('%s_%s', cfg.clusters(c).abbr, cfg.bands(b).name);
        m(key) = struct('cluster', cfg.clusters(c).label, ...
                        'band', cfg.bands(b).label);
    end
end
end
